<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class SanPhamBoSungSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $products = [
            // Điện thoại
            [
                'ten' => 'iPhone 14 Pro Max',
                'sku' => 'IP14PM',
                'loai_san_pham_id' => 1,
                'mo_ta' => 'Điện thoại cao cấp Apple',
                'gia' => 32990000,
                'gia_goc' => 35990000,
                'trong_luong' => 0.24,
                'kich_thuoc' => '160.7x77.6x7.85',
                'mau_sac' => 'Đen',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Apple',
                'xuat_xu' => 'Mỹ',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 10,
                'hinh_anh' => 'images/iphone14.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Samsung Galaxy S23',
                'sku' => 'SGS23',
                'loai_san_pham_id' => 1,
                'mo_ta' => 'Điện thoại Samsung mới nhất',
                'gia' => 24990000,
                'gia_goc' => 26990000,
                'trong_luong' => 0.21,
                'kich_thuoc' => '146.3x70.9x7.6',
                'mau_sac' => 'Xanh',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Samsung',
                'xuat_xu' => 'Hàn Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 15,
                'hinh_anh' => 'images/samsung_s23.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Xiaomi Redmi Note 12',
                'sku' => 'XRN12',
                'loai_san_pham_id' => 1,
                'mo_ta' => 'Điện thoại giá rẻ cấu hình cao',
                'gia' => 5990000,
                'gia_goc' => 6990000,
                'trong_luong' => 0.19,
                'kich_thuoc' => '165.7x76.6x8.1',
                'mau_sac' => 'Trắng',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Xiaomi',
                'xuat_xu' => 'Trung Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 20,
                'hinh_anh' => 'images/redmi_note12.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Laptop
            [
                'ten' => 'MacBook Air M2',
                'sku' => 'MBAIR2',
                'loai_san_pham_id' => 2,
                'mo_ta' => 'Laptop Apple chip M2',
                'gia' => 28990000,
                'gia_goc' => 31990000,
                'trong_luong' => 1.24,
                'kich_thuoc' => '304.1x215x11.3',
                'mau_sac' => 'Bạc',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Apple',
                'xuat_xu' => 'Mỹ',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 8,
                'hinh_anh' => 'images/macbook_air_m2.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Dell XPS 13',
                'sku' => 'DXPS13',
                'loai_san_pham_id' => 2,
                'mo_ta' => 'Laptop mỏng nhẹ cao cấp',
                'gia' => 25990000,
                'gia_goc' => 27990000,
                'trong_luong' => 1.2,
                'kich_thuoc' => '295.7x198.7x14.8',
                'mau_sac' => 'Bạc',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Dell',
                'xuat_xu' => 'Mỹ',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 12,
                'hinh_anh' => 'images/dell_xps13.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'HP Pavilion 15',
                'sku' => 'HPP15',
                'loai_san_pham_id' => 2,
                'mo_ta' => 'Laptop phổ thông cho sinh viên',
                'gia' => 13990000,
                'gia_goc' => 15990000,
                'trong_luong' => 1.7,
                'kich_thuoc' => '360x234x17.9',
                'mau_sac' => 'Xám',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'HP',
                'xuat_xu' => 'Mỹ',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 18,
                'hinh_anh' => 'images/hp_pavilion15.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Phụ kiện
            [
                'ten' => 'Tai nghe Bluetooth Sony',
                'sku' => 'SONYBT',
                'loai_san_pham_id' => 3,
                'mo_ta' => 'Tai nghe không dây chống ồn',
                'gia' => 2990000,
                'gia_goc' => 3490000,
                'trong_luong' => 0.18,
                'kich_thuoc' => '180x170x80',
                'mau_sac' => 'Đen',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Sony',
                'xuat_xu' => 'Nhật Bản',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 30,
                'hinh_anh' => 'images/sony_bt.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Chuột Logitech M331',
                'sku' => 'LOGIM331',
                'loai_san_pham_id' => 3,
                'mo_ta' => 'Chuột không dây yên tĩnh',
                'gia' => 350000,
                'gia_goc' => 400000,
                'trong_luong' => 0.09,
                'kich_thuoc' => '105x67x38',
                'mau_sac' => 'Đỏ',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Logitech',
                'xuat_xu' => 'Thụy Sĩ',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 40,
                'hinh_anh' => 'images/logitech_m331.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Bàn phím cơ AKKO 3087',
                'sku' => 'AKKO3087',
                'loai_san_pham_id' => 3,
                'mo_ta' => 'Bàn phím cơ gaming',
                'gia' => 1290000,
                'gia_goc' => 1490000,
                'trong_luong' => 0.85,
                'kich_thuoc' => '360x140x40',
                'mau_sac' => 'Hồng',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'AKKO',
                'xuat_xu' => 'Trung Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 25,
                'hinh_anh' => 'images/akko_3087.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Thiết bị gia dụng
            [
                'ten' => 'Nồi chiên không dầu Lock&Lock',
                'sku' => 'LLAF',
                'loai_san_pham_id' => 4,
                'mo_ta' => 'Nồi chiên dung tích lớn',
                'gia' => 1990000,
                'gia_goc' => 2290000,
                'trong_luong' => 3.5,
                'kich_thuoc' => '320x320x370',
                'mau_sac' => 'Đen',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Lock&Lock',
                'xuat_xu' => 'Hàn Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 7,
                'hinh_anh' => 'images/locknlock_af.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Máy lọc không khí Xiaomi',
                'sku' => 'XIAOMIAIR',
                'loai_san_pham_id' => 4,
                'mo_ta' => 'Máy lọc không khí thông minh',
                'gia' => 2990000,
                'gia_goc' => 3490000,
                'trong_luong' => 4.2,
                'kich_thuoc' => '240x240x520',
                'mau_sac' => 'Trắng',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Xiaomi',
                'xuat_xu' => 'Trung Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 9,
                'hinh_anh' => 'images/xiaomi_air.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Bình đun siêu tốc Philips',
                'sku' => 'PHILIPSKET',
                'loai_san_pham_id' => 4,
                'mo_ta' => 'Bình đun nước nhanh',
                'gia' => 890000,
                'gia_goc' => 990000,
                'trong_luong' => 1.1,
                'kich_thuoc' => '220x160x250',
                'mau_sac' => 'Bạc',
                'chat_lieu' => 'Inox',
                'hang_san_xuat' => 'Philips',
                'xuat_xu' => 'Hà Lan',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 14,
                'hinh_anh' => 'images/philips_ket.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Thêm các sản phẩm khác cho đủ 15 sản phẩm
            [
                'ten' => 'Oppo Reno8',
                'sku' => 'OPPO8',
                'loai_san_pham_id' => 1,
                'mo_ta' => 'Điện thoại Oppo camera đẹp',
                'gia' => 8990000,
                'gia_goc' => 9990000,
                'trong_luong' => 0.19,
                'kich_thuoc' => '160x73x7.7',
                'mau_sac' => 'Xanh',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Oppo',
                'xuat_xu' => 'Trung Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 17,
                'hinh_anh' => 'images/oppo_reno8.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Lenovo ThinkPad X1',
                'sku' => 'LTPX1',
                'loai_san_pham_id' => 2,
                'mo_ta' => 'Laptop doanh nhân bền bỉ',
                'gia' => 32990000,
                'gia_goc' => 35990000,
                'trong_luong' => 1.1,
                'kich_thuoc' => '323x217x14.9',
                'mau_sac' => 'Đen',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Lenovo',
                'xuat_xu' => 'Trung Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 6,
                'hinh_anh' => 'images/thinkpad_x1.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Ổ cứng SSD Samsung 1TB',
                'sku' => 'SSD1TB',
                'loai_san_pham_id' => 3,
                'mo_ta' => 'Ổ cứng SSD tốc độ cao',
                'gia' => 2490000,
                'gia_goc' => 2990000,
                'trong_luong' => 0.05,
                'kich_thuoc' => '100x70x7',
                'mau_sac' => 'Đen',
                'chat_lieu' => 'Nhôm',
                'hang_san_xuat' => 'Samsung',
                'xuat_xu' => 'Hàn Quốc',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 22,
                'hinh_anh' => 'images/samsung_ssd.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'ten' => 'Máy xay sinh tố Sunhouse',
                'sku' => 'SHBLENDER',
                'loai_san_pham_id' => 4,
                'mo_ta' => 'Máy xay đa năng',
                'gia' => 690000,
                'gia_goc' => 790000,
                'trong_luong' => 1.5,
                'kich_thuoc' => '180x180x380',
                'mau_sac' => 'Xám',
                'chat_lieu' => 'Nhựa',
                'hang_san_xuat' => 'Sunhouse',
                'xuat_xu' => 'Việt Nam',
                'tinh_trang' => 1,
                'luot_xem' => 0,
                'danh_gia_trung_binh' => 0,
                'so_luong_danh_gia' => 0,
                'so_luong_ton_kho' => 11,
                'hinh_anh' => 'images/sunhouse_blender.jpg',
                'hinh_anh_bo_sung' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($products as $product) {
            DB::table('san_phams')->insert($product);
        }
    }
}
